sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build  -t rddill/learn-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true rddill/learn-docker npm run test

deploy: 
    # for deploying to AWS
    # this is AWS Docker support
    provider: elasticbeanstalk 
    # or whichever region used in AWS to create initial holding space for app
    region: "us-east-2" 
    # user provided name at AWS App creation time
    app: "learn-docker" 
    # AWS Environment Name. Found in the elasitic beanstalk space for the app
    env: "LearnDocker-env"
    # bucket name found, complete with UID, from S3 search after initial app creation in AWS
    bucket_name: "elasticbeanstalk-us-east-2-692974209456" 
    # same as app name
    bucket-path: "learn-docker" 
    on:
        # which git branch change will cause this set of instructions to be executed 
        branch: master 
    # this is stored in travis for this git repo
    access_key_id: $AWS_ACCESS_KEY 
    # this is stored in travis for this git repo
    secret_access_key: $AWS_SECRET_KEY 