sudo: required
language: generic 
services: 
    - docker

before_install:
    - docker build  -t rddill/learn-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true rddill/learn-docker npm run test