version: '3'
services: 
    redis-server:
        image: 'redis'
        restart: unless-stopped
    node-app:
        restart: unless-stopped
        build: .
        ports:
            - "6101:6001"