version: '3'
services:
    web:
        environment:
        - CHOKIDAR_USEPOLLING=true 
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - 6101:3000
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
    tests:
        container_name: frontend-test-container
        environment:
        - CHOKIDAR_USEPOLLING=true 
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
